---
title: "Atelier 4"
author: "Emmanuelle Corre"
date: "05/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
nutriage <- read.csv("~/nutriage.csv")
names(nutriage)
```
Taille est normal?

```{r}
mu_taille<-mean(nutriage$taille)
sigma_taille<-sd(nutriage$taille)
mu_taille
sigma_taille
pnorm(0,mu_taille,sigma_taille)
```
Taille $=e^X$ ou $X\sim N(\mu,\sigma)$ alors $X =\ln(\text{Taille})) \sim N(\mu,\sigma)$

```{r}
x<-log(nutriage$taille)
mu_x<-mean(x)
sigma_x<-sd(x)
mu_x
sigma_x
n<-length(x)
n
```
```{r}
z<-(x-mu_x)/sigma_x
t_simul<-rnorm(n)
qqplot(z,t_simul,xlim=c(-3,3),ylim=c(-3,3))
par(new=T)
plot(z,z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3))
```
```{r}
mu_poids<-mean(nutriage$poids)
sigma_poids<-sd(nutriage$poids)
mu_poids
sigma_poids
pnorm(0,mu_poids,sigma_poids)
```
Poids $=e^X$ ou $X\sim N(\mu,\sigma)$ alors $X =\ln(\text{Poids})) \sim N(\mu,\sigma)$

```{r}
x<-log(nutriage$poids)
mu_x<-mean(x)
sigma_x<-sd(x)
mu_x
sigma_x
n<-length(x)
n
```
```{r}
z<-(x-mu_x)/sigma_x
p_simul<-rnorm(n)
qqplot(z,p_simul,xlim=c(-3,3),ylim=c(-3,3))
par(new=T)
plot(z,z,type="l",col="red",xlim=c(-3,3),ylim=c(-3,3))
```
Simulation

```{r}
x<-log(nutriage$poids)
mu_x<-mean(x)
sigma_x<-sd(x)
mu_x
sigma_x
simulation<- rnorm(1000,mu_x,sigma_x)
poids_simul<-exp(simulation)
hist(poids_simul)
```
## Modèle pour la variable café

```{r}
table(nutriage$cafe)/n
mean(nutriage$cafe)
var(nutriage$cafe)
lambda<-(mean(nutriage$cafe)+var(nutriage$cafe))/2
lambda
table(rpois(1000,lambda))
```




